# Generated by Django 5.2.6 on 2025-10-15 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shawarma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('kubbos_per_item', models.IntegerField(default=1)),
                ('quantity_sold', models.IntegerField(default=0)),
            ],
        ),
    ]
